"""End-to-end tests: simulator IQ → STFT → fold_detect.

Verifies that the complete detection pipeline recovers pulsed-CW signals
generated by the simulator using real Telonics VHF collar parameters:
  - tp  = 15 ms  (pulse width)
  - tip = 2.0 s  (resting rate)  / 1.333 s (moving rate)
  - fs  = 3840 Hz (post-decimation sample rate)

Each test generates a full K-fold IQ segment in-process (no sockets), runs
the STFT + fold_detect chain, and checks the detection result.
"""

import numpy as np
import pytest

import pulse_detector
from pulse_detector import (
    admit_lock_candidate,
    amplitude_at_known_pulse,
    build_hypothesis_indices,
    build_weighting_matrix,
    combine_agreeing_locks,
    Detection,
    lock_anchor_fold_index,
    lock_candidate_from_detection,
    lock_snr_db,
    compute_segment_samples,
    compute_stft_power,
    fit_lock_timing,
    fold_detect,
    locks_agree,
    measure_at_lock,
    predict_next_pulse_seconds,
    slice_noise_power,
    measure_at_lock_psd,
    pri_refit_moves_pulses,
    PulseLock,
    promote_to_lock,
    pulse_indices_at_known_phase,
)
from iq_simulator import SimConfig, TagSignal, apply_pri_offset, generate_packet

# ---------------------------------------------------------------------------
# Physical constants
# ---------------------------------------------------------------------------
FS = 3840            # Post-decimation sample rate (Hz)
TP = 0.015           # Pulse width (s)
TIP_REST = 2.0       # Resting inter-pulse interval (s)
TIP_MOVE = 1.333     # Moving inter-pulse interval (s)
PF = 1e-6            # False-alarm probability

# STFT geometry (mirrors pulse_detector main())
N_W = int(np.ceil(TP * FS))               # 58 samples
N_OL = N_W // 2                            # 29 samples
N_WS = N_W - N_OL                          # 29 samples (window step)
N_EXACT = TIP_REST * FS / N_WS            # fractional PRI in windows
N = int(np.floor(N_EXACT))                # integer PRI (resting rate)
N_EXACT_MOVE = TIP_MOVE * FS / N_WS
N_MOVE = int(np.floor(N_EXACT_MOVE))      # integer PRI (moving rate)

# Spectral weighting matrix (computed once for all tests)
W, Wf = build_weighting_matrix(N_W, FS)
NFFT = W.shape[1]


def test_simulator_pri_offset_scales_every_tag_and_keeps_rate_switch_disabled():
    tags = [
        TagSignal(tip=2.0, tip_secondary=1.333, switch_time=34.0),
        TagSignal(tip=3.0, tip_secondary=0.0),
    ]

    apply_pri_offset(tags, 43.0)

    scale = 1.0 + 43e-6
    assert tags[0].tip == pytest.approx(2.0 * scale)
    assert tags[0].tip_secondary == pytest.approx(1.333 * scale)
    assert tags[1].tip == pytest.approx(3.0 * scale)
    # 0.0 means "no rate switch" and must stay exactly 0.0.
    assert tags[1].tip_secondary == 0.0

    # 0 ppm is the ideal crystal: a no-op.
    ideal = [TagSignal(tip=2.0)]
    apply_pri_offset(ideal, 0.0)
    assert ideal[0].tip == 2.0


@pytest.mark.parametrize('ppm', [float('nan'), float('inf'), float('-inf')])
def test_simulator_pri_offset_rejects_non_finite_ppm(ppm):
    # nan/inf are truthy, so a bare `if not ppm` guard would let them scale
    # the TIP to nan/inf and silently mute the tag.
    tags = [TagSignal(tip=2.0)]
    with pytest.raises(ValueError):
        apply_pri_offset(tags, ppm)
    assert tags[0].tip == 2.0


def test_known_pulse_amplitude_subtracts_noise_without_clamping():
    power = np.array([[0.5, 1.5, 0.5, 2.5, 0.5]], dtype=float)

    assert amplitude_at_known_pulse(power, 0, [1, 3], np.array([0.5])) == 3.0
    assert amplitude_at_known_pulse(power, 0, [0, 2, 4], np.array([1.0])) == -1.5


def test_known_pulse_amplitude_ignores_out_of_range_indices():
    power = np.array([[2.0, 3.0]], dtype=float)

    assert amplitude_at_known_pulse(power, 0, [-1, 0, 2], np.array([0.5])) == 1.5
    assert np.isnan(amplitude_at_known_pulse(power, 0, [-2, 4], np.array([0.5])))


def test_known_phase_projects_into_later_segment():
    indices = pulse_indices_at_known_phase(
        segment_start_seconds=104.0, n_time=700, anchor_seconds=100.0,
        pri_seconds=2.0, n_ws=10, fs=100.0, max_pulses=3)

    np.testing.assert_array_equal(indices, [0, 20, 40])


def test_known_phase_projects_into_earlier_segment():
    # A pre-lock buffered segment ends before the anchor; the lock's pulse
    # train still extends backwards into it.
    indices = pulse_indices_at_known_phase(
        segment_start_seconds=88.0, n_time=50, anchor_seconds=100.0,
        pri_seconds=2.0, n_ws=10, fs=100.0, max_pulses=3)

    np.testing.assert_array_equal(indices, [0, 20, 40])


def test_known_phase_earlier_segment_off_grid_start():
    # ceil(-6.35) must give -6 (first pulse at 88.0 s, 0.7 s into the
    # segment); floor would land on 86.0 s, before the segment, and drop a pulse.
    indices = pulse_indices_at_known_phase(
        segment_start_seconds=87.3, n_time=50, anchor_seconds=100.0,
        pri_seconds=2.0, n_ws=10, fs=100.0, max_pulses=3)

    np.testing.assert_array_equal(indices, [7, 27, 47])


def test_measure_at_lock_uses_fixed_frequency_and_phase():
    power = np.ones((3, 50), dtype=float)
    power[1, [0, 20, 40]] = [20.0, 30.0, 40.0]
    power[1, [1, 21, 41]] = [15.0, 15.0, 15.0]

    signal_power, noise_power, indices, n_windows = measure_at_lock(
        power, np.array([-10.0, 0.0, 10.0]), 0.0, 104.0, 100.0, 2.0,
        n_ws=10, fs=100.0, max_pulses=3)

    np.testing.assert_array_equal(indices, [0, 20, 40])
    assert noise_power == 1.0
    assert n_windows == 6
    # Pulse footprint is two half-overlapped windows: idx and idx+1.
    assert signal_power == (20.0 + 30.0 + 40.0) + (3 * 15.0) - 6 * 1.0


def test_measure_at_lock_uses_supplied_noise_power():
    power = np.ones((3, 50), dtype=float)
    power[1, [0, 20, 40]] = [21.0, 21.0, 21.0]
    cached = np.array([1.0, 2.0, 1.0])

    signal_power, noise_power, _, n_windows = measure_at_lock(
        power, np.array([-10.0, 0.0, 10.0]), 0.0, 104.0, 100.0, 2.0,
        n_ws=10, fs=100.0, max_pulses=3, noise_power=cached)

    assert noise_power == 2.0
    assert signal_power == 3 * 21.0 + 3 * 1.0 - n_windows * 2.0


def test_pri_refit_moves_pulses_compares_projected_windows():
    # Anchor at t=0; eight 40 s slices, the farthest ending ~320 s later.
    n_time = int(40.0 * FS / N_WS)
    slices = [{'segment_start_s': 40.0 * i, 'k': 20,
               'power': np.zeros((1, n_time))} for i in range(8)]
    old = PulseLock(0.0, 0.0, 2.0, 5.0)

    def indices(lock):
        return [pulse_indices_at_known_phase(
            s['segment_start_s'], n_time, lock.anchor_seconds,
            lock.pri_seconds, N_WS, FS, s['k']) for s in slices]

    assert not pri_refit_moves_pulses(old, old, slices, N_WS, FS)
    # 20 ppm over 160 PRIs = 6.4 ms: crosses into the next window somewhere.
    assert pri_refit_moves_pulses(
        old, old._replace(pri_seconds=2.0 * (1 + 20e-6)), slices, N_WS, FS)
    # 0.01 ppm over 160 PRIs = 3 us: no projected index can move.
    tiny = old._replace(pri_seconds=2.0 * (1 + 1e-8))
    assert not pri_refit_moves_pulses(old, tiny, slices, N_WS, FS)
    # The verdict must track the actual index arrays, not a distance threshold.
    for ppm in (0.5, 1.0, 2.0, 5.0):
        new = old._replace(pri_seconds=2.0 * (1 + ppm * 1e-6))
        moved = any(not np.array_equal(a, b)
                    for a, b in zip(indices(old), indices(new)))
        assert pri_refit_moves_pulses(old, new, slices, N_WS, FS) == moved


def test_measure_at_lock_clips_footprint_at_segment_end():
    # Last pulse starts on the final window, so its second footprint window
    # falls off the end; the reported count must match what was summed.
    power = np.ones((1, 41), dtype=float)
    power[0, [0, 1, 20, 21, 40]] = [11.0, 11.0, 11.0, 11.0, 11.0]

    signal_power, _, indices, n_windows = measure_at_lock(
        power, np.array([0.0]), 0.0, 104.0, 100.0, 2.0,
        n_ws=10, fs=100.0, max_pulses=3)

    np.testing.assert_array_equal(indices, [0, 20, 40])
    assert n_windows == 5
    assert signal_power == 5 * 11.0 - 5 * 1.0


def test_measure_at_lock_captures_energy_split_across_window_pair():
    # A 15 ms pulse over half-overlapped 15 ms windows always straddles two
    # adjacent STFT windows. The lock projects to the first; the second holds
    # the remainder. A single-window read would under-report by half.
    power = np.ones((1, 50), dtype=float)
    power[0, [20, 21]] = [11.0, 11.0]

    signal_power, _, indices, _ = measure_at_lock(
        power, np.array([0.0]), 0.0, 104.0, 100.0, 2.0,
        n_ws=10, fs=100.0, max_pulses=2)

    np.testing.assert_array_equal(indices, [0, 20])
    # Index 0 footprint reads two noise windows (1.0 each) and subtracts noise.
    assert signal_power == 20.0


def test_measure_at_lock_psd_converts_buffered_measurement_units():
    power = np.ones((3, 50), dtype=float)
    power[1, [0, 20, 40]] = [20.0, 30.0, 40.0]

    signal_power_psd, noise_power_psd, indices, n_windows = measure_at_lock_psd(
        power, np.array([-10.0, 0.0, 10.0]), 0.0, 104.0, 100.0, 2.0,
        n_ws=10, fs=100.0, n_w=20, max_pulses=3)

    np.testing.assert_array_equal(indices, [0, 20, 40])
    assert n_windows == 6
    assert noise_power_psd == pytest.approx(1.0 / 2000.0)
    assert signal_power_psd == pytest.approx(87.0 / 2000.0)


def test_lock_snr_db_matches_fold_definition():
    # Noise-subtracted 87 over 6 windows of unit noise: on-window sum is 93.
    assert lock_snr_db(87.0, 1.0, 6) == pytest.approx(10.0 * np.log10(93.0))
    # PSD scaling cancels in the ratio.
    assert lock_snr_db(87.0 / 2000.0, 1.0 / 2000.0, 6) == pytest.approx(
        10.0 * np.log10(93.0))
    # Pure noise reports 10*log10(n_windows).
    assert lock_snr_db(0.0, 1.0, 10) == pytest.approx(10.0)
    # Over-subtracted or degenerate inputs clamp instead of raising.
    assert lock_snr_db(-20.0, 1.0, 6) == 0.0
    assert lock_snr_db(5.0, 0.0, 6) == 0.0


def test_lock_qualification_requires_frequency_and_phase_agreement():
    previous = PulseLock(100.0, 10.0, 2.0, 4.0)

    assert locks_agree(previous, PulseLock(250.0, 14.005, 2.0, 3.5),
                       frequency_tolerance_hz=200.0,
                       pri_tolerance_seconds=0.01,
                       phase_tolerance_seconds=0.01)
    assert not locks_agree(previous, PulseLock(350.0, 14.005, 2.0, 3.5),
                           frequency_tolerance_hz=200.0,
                           pri_tolerance_seconds=0.01,
                           phase_tolerance_seconds=0.01)
    assert not locks_agree(previous, PulseLock(100.0, 14.02, 2.0, 3.5),
                           frequency_tolerance_hz=200.0,
                           pri_tolerance_seconds=0.01,
                           phase_tolerance_seconds=0.01)
    # Same frequency and phase, different rate hypothesis.
    assert not locks_agree(previous, PulseLock(100.0, 14.0, 1.5, 3.5),
                           frequency_tolerance_hz=200.0,
                           pri_tolerance_seconds=0.01,
                           phase_tolerance_seconds=0.01)


def test_agreeing_locks_refine_pri():
    combined = combine_agreeing_locks(
        PulseLock(100.0, 10.0, 2.0, 4.0),
        PulseLock(120.0, 14.001, 2.0, 3.5))

    assert combined.freq_hz == 110.0
    assert abs(combined.pri_seconds - 2.0005) < 1e-12
    assert combined.anchor_seconds == 10.0


def test_lock_phase_tolerance_widens_with_pri_uncertainty():
    # 100 ppm of PRI uncertainty over 300 s is 30 ms of phase slop; a
    # sighting 20 ms off the projection is the same train. At 1 ppm it isn't.
    loose = PulseLock(100.0, 10.0, 2.0, 4.0, pri_ppm_uncertainty=100.0)
    tight = PulseLock(100.0, 10.0, 2.0, 4.0, pri_ppm_uncertainty=1.0)
    later = PulseLock(100.0, 310.020, 2.0, 3.5)
    tol = dict(frequency_tolerance_hz=200.0, pri_tolerance_seconds=0.01,
               phase_tolerance_seconds=0.0075)

    assert locks_agree(loose, later, **tol)
    assert not locks_agree(tight, later, **tol)


# Real geometry: 3840 S/s, 15 ms pulse, 50% overlap -> 7.55 ms STFT step.
_FIT_N_WS = 29
_FIT_FS = 3840.0
_FIT_K = 20


def _rotation_slices(true_pri, n_slices=8, anchor=1.0, pulse_power=10.0):
    """n_slices consecutive K-pulse spectrograms of a train at true_pri."""
    n_time = int(np.ceil(_FIT_K * true_pri * _FIT_FS / _FIT_N_WS))
    seg_len_s = n_time * _FIT_N_WS / _FIT_FS
    slices = []
    for s in range(n_slices):
        seg_start = s * seg_len_s
        power = np.ones((3, n_time), dtype=np.float32)
        first = int(np.ceil((seg_start - anchor) / true_pri))
        for n in range(first, first + _FIT_K + 2):
            t = anchor + n * true_pri
            idx = int(np.rint((t - seg_start) * _FIT_FS / _FIT_N_WS))
            if 0 <= idx < n_time:
                power[1, idx] = pulse_power
                if idx + 1 < n_time:
                    power[1, idx + 1] = pulse_power
        slices.append({'power': power, 'segment_start_s': seg_start,
                       'k': _FIT_K, 'slice_id': s + 1})
    return slices


_FIT_FREQ_AXIS = np.array([-10.0, 0.0, 10.0])


@pytest.mark.parametrize('true_ppm', [43.0, 150.0, -80.0])
def test_fit_lock_timing_recovers_collar_pri_offset(true_ppm):
    true_pri = 2.0 * (1.0 + true_ppm * 1e-6)
    slices = _rotation_slices(true_pri)
    nominal = PulseLock(0.0, 1.0, 2.0, 5.0, nominal_pri_seconds=2.0)

    fitted = fit_lock_timing(slices, _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)

    fitted_ppm = (fitted.pri_seconds / 2.0 - 1.0) * 1e6
    assert fitted_ppm == pytest.approx(true_ppm, abs=10.0)
    assert fitted.pri_ppm_uncertainty <= 15.0
    assert fitted.anchor_seconds == nominal.anchor_seconds
    assert fitted.freq_hz == nominal.freq_hz


def test_fit_lock_timing_recovers_far_heading_amplitude():
    # 43 ppm over 160 pulses is ~13 ms of drift, nearly two STFT steps: the
    # last heading measured at the nominal PRI reads near zero.
    true_pri = 2.0 * (1.0 + 43e-6)
    slices = _rotation_slices(true_pri)
    nominal = PulseLock(0.0, 1.0, 2.0, 5.0, nominal_pri_seconds=2.0)
    last = slices[-1]

    def amplitude(lock):
        signal, _, _, _ = measure_at_lock(
            last['power'], _FIT_FREQ_AXIS, lock.freq_hz, last['segment_start_s'],
            lock.anchor_seconds, lock.pri_seconds, _FIT_N_WS, _FIT_FS, last['k'])
        return signal

    full = _FIT_K * 2 * (10.0 - 1.0)
    assert amplitude(nominal) < 0.5 * full

    fitted = fit_lock_timing(slices, _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)
    assert amplitude(fitted) > 0.9 * full


def test_fit_lock_timing_uncertainty_shrinks_with_rotation_length():
    true_pri = 2.0 * (1.0 + 43e-6)
    nominal = PulseLock(0.0, 1.0, 2.0, 5.0, nominal_pri_seconds=2.0)

    one = fit_lock_timing(_rotation_slices(true_pri, n_slices=1),
                          _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)
    eight = fit_lock_timing(_rotation_slices(true_pri, n_slices=8),
                            _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)

    # A PRI error grows with distance from the anchor, so eight dwells pin
    # it tighter than one.
    assert eight.pri_ppm_uncertainty < one.pri_ppm_uncertainty


def test_fit_lock_timing_stays_centred_on_nominal_pri():
    # The grid is anchored to the collar's nominal PRI, not the last estimate,
    # so a noise-driven refit cannot random-walk out of the search window.
    slices = _rotation_slices(2.0 * (1.0 + 43e-6))
    drifted = PulseLock(0.0, 1.0, 2.0 * (1.0 + 250e-6), 5.0,
                        nominal_pri_seconds=2.0)

    fitted = fit_lock_timing(slices, _FIT_FREQ_AXIS, drifted, _FIT_N_WS, _FIT_FS)

    assert (fitted.pri_seconds / 2.0 - 1.0) * 1e6 == pytest.approx(43.0, abs=10.0)
    assert fitted.nominal_pri_seconds == 2.0


def test_fit_lock_timing_rejects_lock_without_nominal_pri():
    slices = _rotation_slices(2.0)
    with pytest.raises(ValueError, match='nominal_pri_seconds'):
        fit_lock_timing(slices, _FIT_FREQ_AXIS, PulseLock(0.0, 1.0, 2.0, 5.0),
                        _FIT_N_WS, _FIT_FS)


def _zero_fill(slice_, start, end):
    """Emulate a dropped-packet hole covering STFT windows start..end."""
    slice_['power'][:, start:end + 1] = 0.0
    slice_['had_gap'] = True
    slice_['gap_windows'] = [(start, end)]


def test_fit_lock_timing_ignores_zero_filled_windows():
    # A hole in the last (most PRI-sensitive) slice swallows a run of pulses.
    # Zero power minus noise on the projected footprint would be counted as
    # evidence against whichever PRI lands there; masked, the fit matches the
    # clean rotation exactly.
    true_pri = 2.0 * (1.0 + 43e-6)
    nominal = PulseLock(0.0, 1.0, 2.0, 5.0, nominal_pri_seconds=2.0)
    clean = fit_lock_timing(_rotation_slices(true_pri), _FIT_FREQ_AXIS, nominal,
                            _FIT_N_WS, _FIT_FS)

    gapped = _rotation_slices(true_pri)
    n_time = gapped[-1]['power'].shape[1]
    _zero_fill(gapped[-1], n_time // 4, (3 * n_time) // 4)
    masked = fit_lock_timing(gapped, _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)

    assert masked.pri_seconds == pytest.approx(clean.pri_seconds, abs=1e-9)
    assert masked.pri_ppm_uncertainty == clean.pri_ppm_uncertainty


def test_fit_lock_timing_all_gap_slice_is_inert():
    true_pri = 2.0 * (1.0 + 43e-6)
    nominal = PulseLock(0.0, 1.0, 2.0, 5.0, nominal_pri_seconds=2.0)
    slices = _rotation_slices(true_pri)
    without = fit_lock_timing(slices[:-1], _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)

    n_time = slices[-1]['power'].shape[1]
    _zero_fill(slices[-1], 0, n_time - 1)
    with_gap = fit_lock_timing(slices, _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)

    assert with_gap == without


def test_fit_lock_timing_returns_lock_when_everything_is_gap():
    nominal = PulseLock(0.0, 1.0, 2.0, 5.0, nominal_pri_seconds=2.0)
    slices = _rotation_slices(2.0, n_slices=2)
    for s in slices:
        _zero_fill(s, 0, s['power'].shape[1] - 1)

    assert fit_lock_timing(slices, _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS) == nominal


def test_fit_lock_timing_hypothesis_with_no_data_cannot_win():
    # Pure noise slightly above the cached estimate, so every hypothesis that
    # touches data scores negative. Gap out exactly the windows the +40 ppm
    # hypothesis projects onto in every slice: it (and its window-sharing
    # neighbours) would score 0 and "win" despite having no evidence at all.
    nominal = PulseLock(0.0, 1.0, 2.0, 5.0, nominal_pri_seconds=2.0)
    slices = _rotation_slices(2.0, pulse_power=1.0)
    for s in slices:
        s['power'][:] = 1.0
        s['noise_power'] = np.full(3, 1.1)
        n_time = s['power'].shape[1]
        idx = pulse_indices_at_known_phase(
            s['segment_start_s'], n_time, 1.0, 2.0 * (1 + 40e-6),
            _FIT_N_WS, _FIT_FS, s['k'])
        s['had_gap'] = True
        s['gap_windows'] = [(int(i), int(i) + 1) for i in idx]

    fitted = fit_lock_timing(slices, _FIT_FREQ_AXIS, nominal, _FIT_N_WS, _FIT_FS)

    # Whatever the noise-only fit settles on, it must not be the data-free
    # band presented as a tight estimate.
    fitted_ppm = (fitted.pri_seconds / 2.0 - 1.0) * 1e6
    assert abs(fitted_ppm - 40.0) > fitted.pri_ppm_uncertainty


def test_slice_noise_power_ignores_zero_filled_columns():
    rng = np.random.default_rng(0)
    power = rng.exponential(1.0, size=(3, 400)).astype(np.float32)
    clean = slice_noise_power(power, [])

    gapped = power.copy()
    gapped[:, 100:300] = 0.0
    masked = slice_noise_power(gapped, [(100, 299)])
    unmasked = slice_noise_power(gapped, [])

    assert unmasked[1] < 0.9 * clean[1]           # zeros drag the estimate down
    assert masked == pytest.approx(clean, rel=0.15)  # same population, half the samples
    # All gap: fall back to the full array rather than an empty one.
    assert slice_noise_power(gapped, [(0, 399)]).shape == (3,)


def test_fit_lock_timing_flags_clipped_plateau_and_keeps_prior():
    # A collar 400 ppm off sits outside the ±300 ppm grid: the energy maximum
    # is pinned to the edge. The prior must survive with a widened
    # uncertainty rather than the edge value posing as a converged fit.
    slices = _rotation_slices(2.0 * (1.0 + 400e-6))
    prior = PulseLock(0.0, 1.0, 2.0 * (1.0 + 43e-6), 5.0,
                      nominal_pri_seconds=2.0, pri_ppm_uncertainty=20.0)

    fitted = fit_lock_timing(slices, _FIT_FREQ_AXIS, prior, _FIT_N_WS, _FIT_FS)

    assert fitted.pri_fit_clipped
    assert fitted.pri_seconds == prior.pri_seconds
    assert fitted.pri_ppm_uncertainty == 300.0

    # An in-range collar is not flagged.
    good = fit_lock_timing(_rotation_slices(2.0 * (1.0 + 43e-6)), _FIT_FREQ_AXIS,
                           prior, _FIT_N_WS, _FIT_FS)
    assert not good.pri_fit_clipped


def test_predict_next_pulse_follows_train_through_dropped_pulses():
    # 2 s PRI is ~265 STFT steps; the third pulse was dropped by a gap.
    seg_start, n_ws, fs, pri = 1000.0, 29, 3840.0, 2.0
    step = pri * fs / n_ws
    full = np.rint(10 + step * np.arange(4)).astype(np.int64)
    sparse = full[[0, 1, 3]]
    n_time = int(full[-1] + 20)

    expected = seg_start + full[-1] * n_ws / fs + pri
    assert predict_next_pulse_seconds(seg_start, full, n_time, n_ws, fs, pri) == pytest.approx(expected, abs=1e-3)
    assert predict_next_pulse_seconds(seg_start, sparse, n_time, n_ws, fs, pri) == pytest.approx(expected, abs=1e-3)
    # The old first + count * PRI form lands a whole PRI short on the sparse train.
    old = seg_start + sparse[0] * n_ws / fs + sparse.size * pri
    assert old == pytest.approx(expected - pri, abs=n_ws / fs)


def test_predict_next_pulse_clears_segment_when_trailing_pulses_gapped():
    # Last two pulses fell in a gap: advancing one PRI from the last kept
    # pulse would still be inside the completed segment.
    seg_start, n_ws, fs, pri = 1000.0, 29, 3840.0, 2.0
    step = pri * fs / n_ws
    full = np.rint(10 + step * np.arange(4)).astype(np.int64)
    kept = full[:2]
    n_time = int(full[-1] + 20)
    seg_end = seg_start + n_time * n_ws / fs

    predicted = predict_next_pulse_seconds(seg_start, kept, n_time, n_ws, fs, pri)
    assert predicted >= seg_end
    # ...and it is still on the train: a whole number of PRIs from the last kept pulse.
    cycles = (predicted - (seg_start + kept[-1] * n_ws / fs)) / pri
    assert cycles == pytest.approx(round(cycles), abs=1e-9)
    assert predicted == pytest.approx(seg_start + full[-1] * n_ws / fs + pri, abs=n_ws / fs)


def test_measure_at_lock_drops_pulses_touching_gap_windows():
    true_pri = 2.0
    lock = PulseLock(0.0, 1.0, true_pri, 5.0, nominal_pri_seconds=2.0)
    clean = _rotation_slices(true_pri, n_slices=1)[0]
    n_time = clean['power'].shape[1]
    # Fixed noise so the comparison isolates the footprint selection.
    noise = np.ones(3)
    full_signal, _, full_idx, full_windows = measure_at_lock(
        clean['power'], _FIT_FREQ_AXIS, lock.freq_hz, clean['segment_start_s'],
        lock.anchor_seconds, lock.pri_seconds, _FIT_N_WS, _FIT_FS, clean['k'],
        noise_power=noise)
    per_pulse = full_signal / full_idx.size

    gapped = _rotation_slices(true_pri, n_slices=1)[0]
    _zero_fill(gapped, n_time // 3, n_time // 2)

    # Unmasked: zeroed footprints subtract noise and still count as pulses.
    biased, _, biased_idx, _ = measure_at_lock(
        gapped['power'], _FIT_FREQ_AXIS, lock.freq_hz, gapped['segment_start_s'],
        lock.anchor_seconds, lock.pri_seconds, _FIT_N_WS, _FIT_FS, gapped['k'],
        noise_power=noise)
    assert biased_idx.size == full_idx.size
    assert biased / biased_idx.size < 0.9 * per_pulse

    # Masked: fewer pulses, same per-pulse power, no footprint in the hole.
    signal, _, idx, n_windows = measure_at_lock(
        gapped['power'], _FIT_FREQ_AXIS, lock.freq_hz, gapped['segment_start_s'],
        lock.anchor_seconds, lock.pri_seconds, _FIT_N_WS, _FIT_FS, gapped['k'],
        noise_power=noise, gap_windows=gapped['gap_windows'])
    assert 0 < idx.size < full_idx.size
    assert n_windows == 2 * idx.size
    assert signal / idx.size == pytest.approx(per_pulse, rel=1e-6)
    lo, hi = gapped['gap_windows'][0]
    assert not np.any((idx + 1 >= lo) & (idx <= hi))


_BANK_TOL = dict(frequency_tolerance_hz=200.0, pri_tolerance_seconds=0.01,
                 phase_tolerance_seconds=0.01)


def test_candidate_bank_admits_distinct_and_merges_agreeing():
    bank = []
    assert admit_lock_candidate(bank, PulseLock(100.0, 10.0, 2.0, 4.0), **_BANK_TOL) == (0, 'admitted')
    # Different frequency: a competing candidate, not a confirmation.
    assert admit_lock_candidate(bank, PulseLock(900.0, 10.0, 2.0, 3.5), **_BANK_TOL) == (1, 'admitted')
    assert len(bank) == 2
    # Same train seen again two PRIs later: merges into entry 0 and confirms it.
    assert admit_lock_candidate(
        bank, PulseLock(120.0, 14.001, 2.0, 5.0), **_BANK_TOL) == (0, 'merged')
    assert len(bank) == 2
    assert bank[0].freq_hz == 110.0
    assert abs(bank[0].pri_seconds - 2.0005) < 1e-12


def test_candidate_bank_is_bounded_and_evicts_weakest():
    bank = []
    for i in range(4):
        admit_lock_candidate(bank, PulseLock(1000.0 * i, 10.0, 2.0, 3.0 + i),
                             max_candidates=4, **_BANK_TOL)
    assert len(bank) == 4
    # Weaker than every entry: dropped.
    assert admit_lock_candidate(bank, PulseLock(-1000.0, 10.0, 2.0, 2.0),
                                max_candidates=4, **_BANK_TOL) == (None, 'dropped')
    # Stronger than the weakest (entry 0, score 3.0): replaces it.
    assert admit_lock_candidate(bank, PulseLock(-1000.0, 10.0, 2.0, 3.5),
                                max_candidates=4, **_BANK_TOL) == (0, 'replaced')
    assert bank[0].freq_hz == -1000.0


def test_candidate_bank_is_frozen_once_locked():
    # Reported ids must stay valid: no merges, no evictions, append only.
    bank = [PulseLock(0.0, 10.0, 2.0, 3.0), PulseLock(1000.0, 10.0, 2.0, 9.0)]
    assert admit_lock_candidate(bank, PulseLock(20.0, 14.0, 2.0, 50.0),
                                locked=True, **_BANK_TOL) == (0, 'seen')
    assert bank[0] == PulseLock(0.0, 10.0, 2.0, 3.0)
    assert admit_lock_candidate(bank, PulseLock(-1500.0, 10.0, 2.0, 4.0),
                                locked=True, **_BANK_TOL) == (2, 'admitted')
    assert admit_lock_candidate(bank, PulseLock(1800.0, 10.0, 2.0, 99.0),
                                max_candidates=3, locked=True,
                                **_BANK_TOL) == (None, 'dropped')
    assert len(bank) == 3


def test_candidate_bank_keeps_sightings_in_lockstep():
    # The bank owns the per-candidate sighting record so the two can never
    # diverge: every event that touches an entry touches its sightings.
    bank, sightings = [], []
    admit_lock_candidate(bank, PulseLock(100.0, 10.0, 2.0, 4.0),
                         sightings=sightings, slice_id=1, **_BANK_TOL)
    admit_lock_candidate(bank, PulseLock(900.0, 10.0, 2.0, 3.5),
                         sightings=sightings, slice_id=1, **_BANK_TOL)
    assert sightings == [{1: 4.0}, {1: 3.5}]

    # Second sighting of entry 0 on another slice keeps the stronger score per slice.
    admit_lock_candidate(bank, PulseLock(110.0, 14.001, 2.0, 5.0),
                         sightings=sightings, slice_id=2, **_BANK_TOL)
    admit_lock_candidate(bank, PulseLock(110.0, 14.001, 2.0, 4.5),
                         sightings=sightings, slice_id=2, **_BANK_TOL)
    assert sightings[0] == {1: 4.0, 2: 5.0}

    # Eviction of the weakest resets its record.
    admit_lock_candidate(bank, PulseLock(-900.0, 10.0, 2.0, 6.0),
                         sightings=sightings, slice_id=3, max_candidates=2, **_BANK_TOL)
    assert bank[1].freq_hz == -900.0
    assert sightings[1] == {3: 6.0}

    # A post-lock 'seen' records the sighting without touching the lock.
    admit_lock_candidate(bank, PulseLock(-900.0, 16.0, 2.0, 7.0),
                         sightings=sightings, slice_id=4, locked=True, **_BANK_TOL)
    assert sightings[1] == {3: 6.0, 4: 7.0}
    assert len(bank) == len(sightings) == 2

    # Promotion reorders both lists together.
    promote_to_lock(bank, sightings, 1)
    assert bank[0].freq_hz == -900.0
    assert sightings[0] == {3: 6.0, 4: 7.0}


def _detection_with_windows(hyp_label, windows):
    return Detection(freq_hz=0.0, snr_db=20.0, signal_power=1.0, offset=windows[0],
                     noise_psd=1e-10, stft_score=1.0, score_ratio=40.0,
                     hyp_label=hyp_label,
                     fold_info={'max_fold_fraction': 0.2, 'fold_snrs': [],
                                'fold_windows': windows})


def test_switch_hypothesis_lock_anchors_on_final_rate_train():
    # Pulses 0..1 at rate A (spacing 10), then rate B (spacing 15) from pulse 2.
    windows = [100, 110, 120, 135, 150]
    assert lock_anchor_fold_index('A') == 0
    assert lock_anchor_fold_index('B') == 0
    assert lock_anchor_fold_index('A_to_B_c2') == 2
    assert lock_anchor_fold_index('B_to_A_c3') == 3

    lock = lock_candidate_from_detection(
        _detection_with_windows('A_to_B_c2', windows),
        segment_start_seconds=0.0, n_ws=10, fs=100.0, pri_seconds=1.5)
    # Anchored at pulse 2 (window 120 -> 12.0 s); projecting PRI B lands on
    # the real B pulses (13.5 s, 15.0 s). Anchoring at pulse 0 would put the
    # projected train at 11.5/13.0 s, off every real pulse.
    assert lock.anchor_seconds == pytest.approx(12.0)
    assert lock.anchor_seconds + lock.pri_seconds == pytest.approx(13.5)

    pure = lock_candidate_from_detection(
        _detection_with_windows('A', windows),
        segment_start_seconds=0.0, n_ws=10, fs=100.0, pri_seconds=1.0)
    assert pure.anchor_seconds == pytest.approx(10.0)


@pytest.mark.parametrize('f0', [0.0, 300.0, -800.0, 1500.0])
def test_weighting_matrix_labels_pure_tone(f0):
    """W applied to an fftshift'ed window DFT must peak at the Wf entry
    nearest the tone frequency."""
    x = np.exp(2j * np.pi * f0 * np.arange(N_W) / FS)
    S = np.fft.fftshift(np.fft.fft(x))
    scores = np.abs(W.conj().T @ S) ** 2
    assert abs(Wf[np.argmax(scores)] - f0) <= FS / NFFT

# ---------------------------------------------------------------------------
# Shared EVT cache pool — keyed by (K, N_B) so single-rate and dual-rate
# configurations get independent EVT thresholds.
# ---------------------------------------------------------------------------
_evt_pool: dict[tuple, dict] = {}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _fold_offsets(K: int, tip: float = TIP_REST) -> np.ndarray:
    N_exact = tip * FS / N_WS
    return np.round(np.arange(K) * N_exact).astype(int)


def _generate_segment(K: int, snr_db: float, freq_offset_hz: float = 0.0,
                      tip: float = TIP_REST, seed: int = 42) -> np.ndarray:
    """Generate a continuous IQ segment covering K pulse intervals."""
    N_A_exact = tip * FS / N_WS
    samples_needed = compute_segment_samples(N_WS, N_OL, K, N_A_exact)

    cfg = SimConfig(
        sample_rate=FS,
        samples_per_packet=samples_needed,
        noise_power_dbfs=-40.0,
        tags=[TagSignal(
            freq_offset_hz=freq_offset_hz,
            snr_db=snr_db,
            tp=TP,
            tip=tip,
        )],
        seed=seed,
    )
    rng = np.random.default_rng(cfg.seed)
    return generate_packet(cfg, sample_offset=0, rng=rng, telem_state=None)


def _run_detect(K: int, snr_db: float, freq_offset_hz: float = 0.0,
                tip: float = TIP_REST, seed: int = 42,
                detection_margin: float = 0.90, frequency_mask=None,
                max_detections: int = 1, extra_tags=()):
    """Full pipeline: generate IQ → STFT → fold_detect. Returns fold_detect output."""
    old_K = pulse_detector.K
    pulse_detector.K = K
    try:
        N_A_exact = tip * FS / N_WS
        fo = _fold_offsets(K, tip)
        samples_needed = compute_segment_samples(N_WS, N_OL, K, N_A_exact)
        if extra_tags:
            cfg = SimConfig(
                sample_rate=FS, samples_per_packet=samples_needed,
                noise_power_dbfs=-40.0,
                tags=[TagSignal(freq_offset_hz=freq_offset_hz, snr_db=snr_db,
                                tp=TP, tip=tip)] + list(extra_tags),
                seed=seed)
            iq = generate_packet(cfg, sample_offset=0,
                                 rng=np.random.default_rng(seed), telem_state=None)
        else:
            iq = _generate_segment(K, snr_db, freq_offset_hz, tip, seed)

        power, n_win = compute_stft_power(iq, N_W, N_OL, NFFT, W=W)

        # Per-(K, N_B) EVT cache so different configurations get independent thresholds
        cache = _evt_pool.setdefault((K, None), {})

        return fold_detect(
            power, N, PF, FS, NFFT, N_W, N_OL, samples_needed,
            cache,
            fold_offsets=fo,
            W=W, Wf=Wf,
            detection_margin=detection_margin,
            frequency_mask=frequency_mask,
            max_detections=max_detections,
        )
    finally:
        pulse_detector.K = old_K


def test_fold_detect_rejects_geometry_that_disagrees_with_k_folds():
    # k_folds keys the EVT threshold: a mismatch with the folded geometry
    # would silently apply the wrong false-alarm threshold.
    power = np.ones((NFFT, 3000), dtype=np.float32)
    offsets_k5 = _fold_offsets(5, TIP_REST)
    with pytest.raises(ValueError, match='fold_offsets has 5 folds but k_folds=20'):
        fold_detect(power, N, PF, FS, NFFT, N_W, N_OL, 1, {},
                    fold_offsets=offsets_k5, W=W, Wf=Wf, k_folds=20)
    hyps_k5 = build_hypothesis_indices(N_EXACT, 5, 3000, N_EXACT_MOVE)
    with pytest.raises(ValueError, match=r'built for \[5\] folds but k_folds=20'):
        fold_detect(power, N, PF, FS, NFFT, N_W, N_OL, 1, {},
                    hypotheses=hyps_k5, W=W, Wf=Wf, k_folds=20)
    with pytest.raises(ValueError, match='k_folds must be >= 1'):
        fold_detect(power, N, PF, FS, NFFT, N_W, N_OL, 1, {},
                    fold_offsets=offsets_k5, W=W, Wf=Wf, k_folds=0)


def test_fold_detect_returns_extra_peaks_only_when_asked():
    # Two trains 1 kHz apart: the default single-peak result keeps reports
    # single, while the candidate bank asks for the alternates.
    second = TagSignal(freq_offset_hz=1000.0, snr_db=20.0, tp=TP, tip=TIP_REST)
    single, _, _ = _run_detect(5, snr_db=25.0, seed=91, extra_tags=[second])
    assert len(single) == 1
    assert abs(single[0].freq_hz) < 100.0

    multi, _, _ = _run_detect(5, snr_db=25.0, seed=91, extra_tags=[second],
                              max_detections=4)
    # At 25 dB a spectral sidelobe may also clear the threshold, so only the
    # ordering and the two real trains are asserted.
    assert 2 <= len(multi) <= 4
    assert abs(multi[0].freq_hz) < 100.0            # strongest first
    assert any(abs(d.freq_hz - 1000.0) < 100.0 for d in multi[1:])
    assert all(multi[i].snr_db >= multi[i + 1].snr_db
               for i in range(len(multi) - 1))


def test_evt_threshold_cache_invalidates_when_search_space_changes():
    # The threshold is a max over the searched bins. A caller that keeps one
    # cache dict but narrows the frequency mask must not reuse the wider
    # threshold; fold_detect itself has to detect the change.
    K = 5
    cache = _evt_pool.setdefault((K, None), {})
    _run_detect(K, snr_db=25.0)
    full_key = cache['search_key']
    full_threshold = cache['threshold']
    assert full_key == (1, NFFT)

    narrow_mask = np.abs(Wf) <= 200.0
    _run_detect(K, snr_db=25.0, frequency_mask=narrow_mask)
    assert cache['search_key'] == (1, int(np.count_nonzero(narrow_mask)))
    # Regenerated for the narrow mask, not reused from the full search.
    assert cache['threshold'] is not None
    assert cache['threshold'] != full_threshold

    # Restore the shared pool entry for later tests.
    _run_detect(K, snr_db=25.0)
    assert cache['search_key'] == full_key


# ===================================================================
# K = 5 (default fold count)
# ===================================================================
class TestSingleRateK5:
    K = 5

    def test_strong_signal_detected(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1, "Strong signal (25 dB) should be detected"

    def test_strong_signal_snr_reasonable(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        best = max(detections, key=lambda d: d[1])
        assert best[1] > 10.0, f"Detected SNR {best[1]:.1f} dB unexpectedly low"

    def test_strong_signal_frequency_accuracy(self):
        """Two signals at different offsets should produce detections
        separated by the correct frequency difference."""
        d1, _, _ = _run_detect(self.K, snr_db=25.0, freq_offset_hz=0.0, seed=50)
        d2, _, _ = _run_detect(self.K, snr_db=25.0, freq_offset_hz=200.0, seed=50)
        assert len(d1) >= 1 and len(d2) >= 1
        f1 = max(d1, key=lambda d: d[1])[0]
        f2 = max(d2, key=lambda d: d[1])[0]
        freq_diff = f2 - f1
        bin_width = FS / NFFT
        assert abs(freq_diff - 200.0) < 2 * bin_width, (
            f"Frequency difference {freq_diff:.1f} Hz, expected ~200 Hz "
            f"(tolerance {2*bin_width:.1f} Hz)")

    def test_frequency_prior_confines_reported_candidates(self):
        frequency_mask = np.abs(Wf) <= 200.0
        detections, _, best_candidate = _run_detect(
            self.K, snr_db=25.0, freq_offset_hz=1200.0, seed=50,
            frequency_mask=frequency_mask)

        assert all(abs(detection.freq_hz) <= 200.0 for detection in detections)
        if not detections:
            assert best_candidate is not None
            assert abs(best_candidate['freq_hz']) <= 200.0

    def test_frequency_mask_rejects_non_bool_and_wrong_shape(self):
        # An int mask would fancy-index best_scores rather than select bins.
        with pytest.raises(ValueError, match='must be'):
            _run_detect(self.K, snr_db=25.0, seed=50,
                        frequency_mask=(np.abs(Wf) <= 200.0).astype(np.int64))
        with pytest.raises(ValueError, match='must be'):
            _run_detect(self.K, snr_db=25.0, seed=50,
                        frequency_mask=(np.abs(Wf) <= 200.0).tolist())
        with pytest.raises(ValueError, match='does not match'):
            _run_detect(self.K, snr_db=25.0, seed=50,
                        frequency_mask=np.ones(len(Wf) - 1, dtype=bool))
        with pytest.raises(ValueError, match='selects no bins'):
            _run_detect(self.K, snr_db=25.0, seed=50,
                        frequency_mask=np.zeros(len(Wf), dtype=bool))

    @pytest.mark.parametrize('offset_hz', [0.0, 200.0, -500.0, 1200.0])
    def test_absolute_frequency_label(self, offset_hz):
        """Reported freq_hz must be the true baseband offset, not merely
        correct relative to another detection (regression: a double fftshift
        in build_weighting_matrix relabelled every bin by Fs/2)."""
        dets, _, _ = _run_detect(self.K, snr_db=25.0, freq_offset_hz=offset_hz, seed=71)
        assert len(dets) >= 1
        f = max(dets, key=lambda d: d[1])[0]
        bin_width = FS / NFFT
        assert abs(f - offset_hz) < 2 * bin_width, (
            f"Reported {f:+.1f} Hz for a tone at {offset_hz:+.1f} Hz")

    def test_noise_only_no_detection(self):
        detections, noise_psd, _ = _run_detect(self.K, snr_db=-np.inf, seed=99)
        assert len(detections) == 0, "Noise-only segment should produce no detections"
        assert np.isfinite(noise_psd), "Noise PSD should be finite"

    def test_moderate_signal_detected(self):
        detections, _, _ = _run_detect(self.K, snr_db=12.0, seed=7)
        assert len(detections) >= 1, "Moderate signal (12 dB) should be detected with K=5"

    def test_fold_info_present(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1
        assert 'max_fold_fraction' in detections[0].fold_info
        assert 'fold_snrs' in detections[0].fold_info
        assert len(detections[0].fold_info['fold_snrs']) == self.K

    def test_negative_freq_offset(self):
        """A negative offset should produce a detection at a lower
        frequency than a zero-offset signal (modulo spectral wrapping)."""
        d0, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=0.0, seed=60)
        dn, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=-500.0, seed=60)
        assert len(d0) >= 1 and len(dn) >= 1
        f0 = max(d0, key=lambda d: d[1])[0]
        fn = max(dn, key=lambda d: d[1])[0]
        raw_diff = fn - f0
        # Wrap to [-FS/2, FS/2) to handle spectral boundary crossing
        wrapped_diff = ((raw_diff + FS / 2) % FS) - FS / 2
        bin_width = FS / NFFT
        assert abs(wrapped_diff - (-500.0)) < 2 * bin_width, (
            f"Wrapped frequency shift {wrapped_diff:.1f} Hz, expected ~-500 Hz")

    def test_detection_margin_tight(self):
        """Tight margin (0.99) should still detect a strong signal."""
        detections, _, _ = _run_detect(self.K, snr_db=25.0, detection_margin=0.99)
        assert len(detections) >= 1

    def test_reproducibility(self):
        d1, _, _ = _run_detect(self.K, snr_db=20.0, seed=123)
        d2, _, _ = _run_detect(self.K, snr_db=20.0, seed=123)
        assert len(d1) == len(d2)
        if d1:
            assert d1[0][0] == pytest.approx(d2[0][0])
            assert d1[0][1] == pytest.approx(d2[0][1])


# ===================================================================
# K = 20 (long-range mode)
# ===================================================================
class TestSingleRateK20:
    K = 20

    def test_strong_signal_detected(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1

    def test_weak_signal_detected(self):
        """K=20 integration should recover signals below K=5 threshold."""
        detections, _, _ = _run_detect(self.K, snr_db=6.0, seed=42)
        assert len(detections) >= 1, "Weak signal (6 dB) should be detected with K=20"

    def test_noise_only_no_detection(self):
        detections, noise_psd, _ = _run_detect(self.K, snr_db=-np.inf, seed=200)
        assert len(detections) == 0

    def test_k20_snr_exceeds_k5(self):
        """K=20 fold should yield higher SNR than K=5 for the same signal."""
        d5, _, _ = _run_detect(5, snr_db=15.0, seed=300)
        d20, _, _ = _run_detect(20, snr_db=15.0, seed=300)
        assert len(d5) >= 1 and len(d20) >= 1
        snr5 = max(d[1] for d in d5)
        snr20 = max(d[1] for d in d20)
        assert snr20 > snr5, f"K=20 SNR ({snr20:.1f}) should exceed K=5 ({snr5:.1f})"

    def test_fold_offsets_length(self):
        fo = _fold_offsets(self.K)
        assert len(fo) == self.K

    def test_frequency_accuracy(self):
        """Relative frequency accuracy: offset difference should be preserved."""
        d0, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=0.0, seed=300)
        dn, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=-300.0, seed=300)
        assert len(d0) >= 1 and len(dn) >= 1
        f0 = max(d0, key=lambda d: d[1])[0]
        fn = max(dn, key=lambda d: d[1])[0]
        raw_diff = fn - f0
        wrapped_diff = ((raw_diff + FS / 2) % FS) - FS / 2
        bin_width = FS / NFFT
        assert abs(wrapped_diff - (-300.0)) < 2 * bin_width

    def test_max_fold_fraction_present(self):
        """Strong signal should have a reasonable max_fold_fraction."""
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1
        assert 0.0 < detections[0].fold_info['max_fold_fraction'] <= 1.0


# ===================================================================
# Rate-switch helpers
# ===================================================================
_NOISE_POWER_DBFS = -40.0   # Same noise floor as SimConfig default


def _generate_rate_switch_iq(K: int, snr_db: float, change_point: int,
                             direction: str = 'A_to_B',
                             freq_offset_hz: float = 0.0,
                             seed: int = 42) -> tuple[np.ndarray, int]:
    """Generate IQ with a rate switch at the given change-point.

    Args:
        change_point: Number of gaps at the first rate before switching.
            0 = pure second rate, K-1 = pure first rate.
        direction: 'A_to_B' (rest→move) or 'B_to_A' (move→rest).

    Returns:
        (iq, samples_needed) tuple.
    """
    if direction == 'A_to_B':
        spacings_sec = ([TIP_REST] * change_point
                        + [TIP_MOVE] * (K - 1 - change_point))
    else:
        spacings_sec = ([TIP_MOVE] * change_point
                        + [TIP_REST] * (K - 1 - change_point))

    samples_needed = compute_segment_samples(N_WS, N_OL, K, N_EXACT, N_EXACT_MOVE)

    rng = np.random.default_rng(seed)
    noise_sigma = 10.0 ** (_NOISE_POWER_DBFS / 20.0)
    noise = noise_sigma * (
        rng.standard_normal(samples_needed)
        + 1j * rng.standard_normal(samples_needed)
    ) / np.sqrt(2.0)

    signal = np.zeros(samples_needed, dtype=np.complex128)
    if np.isfinite(snr_db):
        # Build pulse start times from spacing schedule
        pulse_times = [0.0]
        for s in spacings_sec:
            pulse_times.append(pulse_times[-1] + s)

        snr_linear = 10.0 ** (snr_db / 10.0)
        amp = noise_sigma * np.sqrt(snr_linear)
        t = np.arange(samples_needed, dtype=np.float64) / FS
        tone = amp * np.exp(2j * np.pi * freq_offset_hz * t)
        pulse_len = int(np.ceil(TP * FS))
        for pt in pulse_times:
            start = int(round(pt * FS))
            end = min(start + pulse_len, samples_needed)
            if start < samples_needed:
                signal[start:end] = tone[start:end]

    return (signal + noise).astype(np.complex64), samples_needed


def _run_detect_rate_switch(K: int, snr_db: float, change_point: int,
                            direction: str = 'A_to_B',
                            freq_offset_hz: float = 0.0,
                            seed: int = 42,
                            detection_margin: float = 0.90):
    """Full pipeline with multi-hypothesis fold_detect."""
    old_K = pulse_detector.K
    pulse_detector.K = K
    try:
        iq, samples_needed = _generate_rate_switch_iq(
            K, snr_db, change_point, direction, freq_offset_hz, seed)

        power, n_win = compute_stft_power(iq, N_W, N_OL, NFFT, W=W)
        hyps = build_hypothesis_indices(N_EXACT, K, n_win, N_B=N_EXACT_MOVE)

        fo = _fold_offsets(K, TIP_REST)
        cache = _evt_pool.setdefault((K, N_MOVE), {})

        return fold_detect(
            power, N, PF, FS, NFFT, N_W, N_OL, samples_needed,
            cache,
            fold_offsets=fo,
            W=W, Wf=Wf,
            detection_margin=detection_margin,
            hypotheses=hyps, N_B=N_MOVE,
        )
    finally:
        pulse_detector.K = old_K


# ===================================================================
# Rate-switch detection (K = 5)
# ===================================================================
class TestRateSwitchK5:
    """Verify rate-switch multi-hypothesis fold detection and SNR preservation."""
    K = 5

    # -- Detection correctness --

    def test_a_to_b_c2_detected(self):
        """A→B switch at change-point 2 should be detected."""
        detections, _, _ = _run_detect_rate_switch(self.K, snr_db=25.0, change_point=2)
        assert len(detections) >= 1
        assert 'A_to_B' in detections[0].hyp_label

    def test_b_to_a_c2_detected(self):
        """B→A switch at change-point 2 should be detected."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=2, direction='B_to_A')
        assert len(detections) >= 1
        assert 'B_to_A' in detections[0].hyp_label

    def test_pure_a_identified_with_dual_hypotheses(self):
        """Pure rate-A signal should be labelled 'A' under dual-rate search."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=self.K - 1)  # all gaps at rate A
        assert len(detections) >= 1
        assert detections[0].hyp_label == 'A'

    def test_pure_b_identified_with_dual_hypotheses(self):
        """Pure rate-B signal should be labelled 'B' under dual-rate search."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=0)  # all gaps at rate B
        assert len(detections) >= 1
        assert detections[0].hyp_label == 'B'

    # -- SNR preservation across rate switch --

    def test_a_to_b_snr_matches_pure_rate(self):
        """A→B switch fold SNR should be comparable to pure rate-A fold SNR.

        Both correctly-matched hypotheses sum K identical-amplitude pulse
        windows, so the fold gain is the same.
        """
        snr_in = 20.0
        seed = 500
        det_a, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=self.K - 1, seed=seed)
        det_sw, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=2, seed=seed)
        assert len(det_a) >= 1 and len(det_sw) >= 1
        snr_a = det_a[0][1]
        snr_sw = det_sw[0][1]
        assert abs(snr_sw - snr_a) < 3.0, (
            f"Switch SNR ({snr_sw:.1f} dB) differs from pure-A "
            f"({snr_a:.1f} dB) by more than 3 dB")

    def test_b_to_a_snr_matches_pure_rate(self):
        """B→A switch fold SNR should be comparable to pure rate-B fold SNR."""
        snr_in = 20.0
        seed = 501
        det_b, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=0, seed=seed)
        det_sw, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=2, direction='B_to_A', seed=seed)
        assert len(det_b) >= 1 and len(det_sw) >= 1
        snr_b = det_b[0][1]
        snr_sw = det_sw[0][1]
        assert abs(snr_sw - snr_b) < 3.0, (
            f"Switch SNR ({snr_sw:.1f} dB) differs from pure-B "
            f"({snr_b:.1f} dB) by more than 3 dB")

    # -- Change-point identification --

    @pytest.mark.parametrize('c', [1, 2, 3])
    def test_a_to_b_change_point(self, c):
        """Each interior A→B change-point should be correctly identified."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=c, seed=600 + c)
        assert len(detections) >= 1
        assert detections[0].hyp_label == f'A_to_B_c{c}'

    @pytest.mark.parametrize('c', [1, 2, 3])
    def test_b_to_a_change_point(self, c):
        """Each interior B→A change-point should be correctly identified."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=c, direction='B_to_A', seed=700 + c)
        assert len(detections) >= 1
        assert detections[0].hyp_label == f'B_to_A_c{c}'

    # -- Edge cases --

    def test_noise_only_dual_rate(self):
        """Noise-only with dual-rate hypotheses should produce no detection."""
        detections, noise_psd, _ = _run_detect_rate_switch(
            self.K, snr_db=-np.inf, change_point=2, seed=99)
        assert len(detections) == 0
        assert np.isfinite(noise_psd)

    def test_max_fold_fraction_correct_switch(self):
        """Correct switch hypothesis should have a reasonable max_fold_fraction."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=2)
        assert len(detections) >= 1
        assert 0.0 < detections[0].fold_info['max_fold_fraction'] <= 1.0

    def test_fold_info_has_k_entries(self):
        """Rate-switch detection fold_info should contain K per-fold SNRs."""
        detections, _, _ = _run_detect_rate_switch(self.K, snr_db=25.0, change_point=2)
        assert len(detections) >= 1
        assert len(detections[0].fold_info['fold_snrs']) == self.K
