"""End-to-end tests: simulator IQ → STFT → fold_detect.

Verifies that the complete detection pipeline recovers pulsed-CW signals
generated by the simulator using real Telonics VHF collar parameters:
  - tp  = 15 ms  (pulse width)
  - tip = 2.0 s  (resting rate)  / 1.333 s (moving rate)
  - fs  = 3840 Hz (post-decimation sample rate)

Each test generates a full K-fold IQ segment in-process (no sockets), runs
the STFT + fold_detect chain, and checks the detection result.
"""

import numpy as np
import pytest

import pulse_detector
from pulse_detector import (
    build_hypothesis_indices,
    build_weighting_matrix,
    compute_segment_samples,
    compute_stft_power,
    fold_detect,
)
from iq_simulator import SimConfig, TagSignal, generate_packet

# ---------------------------------------------------------------------------
# Physical constants
# ---------------------------------------------------------------------------
FS = 3840            # Post-decimation sample rate (Hz)
TP = 0.015           # Pulse width (s)
TIP_REST = 2.0       # Resting inter-pulse interval (s)
TIP_MOVE = 1.333     # Moving inter-pulse interval (s)
PF = 1e-6            # False-alarm probability

# STFT geometry (mirrors pulse_detector main())
N_W = int(np.ceil(TP * FS))               # 58 samples
N_OL = N_W // 2                            # 29 samples
N_WS = N_W - N_OL                          # 29 samples (window step)
N_EXACT = TIP_REST * FS / N_WS            # fractional PRI in windows
N = int(np.floor(N_EXACT))                # integer PRI (resting rate)
N_EXACT_MOVE = TIP_MOVE * FS / N_WS
N_MOVE = int(np.floor(N_EXACT_MOVE))      # integer PRI (moving rate)

# Spectral weighting matrix (computed once for all tests)
W, Wf = build_weighting_matrix(N_W, FS)
NFFT = W.shape[1]

# ---------------------------------------------------------------------------
# Shared EVT cache pool — keyed by (K, N_B) so single-rate and dual-rate
# configurations get independent EVT thresholds.
# ---------------------------------------------------------------------------
_evt_pool: dict[tuple, dict] = {}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _fold_offsets(K: int, tip: float = TIP_REST) -> np.ndarray:
    N_exact = tip * FS / N_WS
    return np.round(np.arange(K) * N_exact).astype(int)


def _generate_segment(K: int, snr_db: float, freq_offset_hz: float = 0.0,
                      tip: float = TIP_REST, seed: int = 42) -> np.ndarray:
    """Generate a continuous IQ segment covering K pulse intervals."""
    N_A_exact = tip * FS / N_WS
    samples_needed = compute_segment_samples(N_WS, N_OL, K, N_A_exact)

    cfg = SimConfig(
        sample_rate=FS,
        samples_per_packet=samples_needed,
        noise_power_dbfs=-40.0,
        tags=[TagSignal(
            freq_offset_hz=freq_offset_hz,
            snr_db=snr_db,
            tp=TP,
            tip=tip,
        )],
        seed=seed,
    )
    rng = np.random.default_rng(cfg.seed)
    return generate_packet(cfg, sample_offset=0, rng=rng, telem_state=None)


def _run_detect(K: int, snr_db: float, freq_offset_hz: float = 0.0,
                tip: float = TIP_REST, seed: int = 42,
                detection_margin: float = 0.90):
    """Full pipeline: generate IQ → STFT → fold_detect. Returns fold_detect output."""
    old_K = pulse_detector.K
    pulse_detector.K = K
    try:
        N_A_exact = tip * FS / N_WS
        fo = _fold_offsets(K, tip)
        samples_needed = compute_segment_samples(N_WS, N_OL, K, N_A_exact)
        iq = _generate_segment(K, snr_db, freq_offset_hz, tip, seed)

        power, n_win = compute_stft_power(iq, N_W, N_OL, NFFT, W=W)

        # Per-(K, N_B) EVT cache so different configurations get independent thresholds
        cache = _evt_pool.setdefault((K, None), {})

        return fold_detect(
            power, N, PF, FS, NFFT, N_W, N_OL, samples_needed,
            cache,
            fold_offsets=fo,
            W=W, Wf=Wf,
            detection_margin=detection_margin,
        )
    finally:
        pulse_detector.K = old_K


# ===================================================================
# K = 5 (default fold count)
# ===================================================================
class TestSingleRateK5:
    K = 5

    def test_strong_signal_detected(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1, "Strong signal (25 dB) should be detected"

    def test_strong_signal_snr_reasonable(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        best = max(detections, key=lambda d: d[1])
        assert best[1] > 10.0, f"Detected SNR {best[1]:.1f} dB unexpectedly low"

    def test_strong_signal_frequency_accuracy(self):
        """Two signals at different offsets should produce detections
        separated by the correct frequency difference."""
        d1, _, _ = _run_detect(self.K, snr_db=25.0, freq_offset_hz=0.0, seed=50)
        d2, _, _ = _run_detect(self.K, snr_db=25.0, freq_offset_hz=200.0, seed=50)
        assert len(d1) >= 1 and len(d2) >= 1
        f1 = max(d1, key=lambda d: d[1])[0]
        f2 = max(d2, key=lambda d: d[1])[0]
        freq_diff = f2 - f1
        bin_width = FS / NFFT
        assert abs(freq_diff - 200.0) < 2 * bin_width, (
            f"Frequency difference {freq_diff:.1f} Hz, expected ~200 Hz "
            f"(tolerance {2*bin_width:.1f} Hz)")

    def test_noise_only_no_detection(self):
        detections, noise_psd, _ = _run_detect(self.K, snr_db=-np.inf, seed=99)
        assert len(detections) == 0, "Noise-only segment should produce no detections"
        assert np.isfinite(noise_psd), "Noise PSD should be finite"

    def test_moderate_signal_detected(self):
        detections, _, _ = _run_detect(self.K, snr_db=12.0, seed=7)
        assert len(detections) >= 1, "Moderate signal (12 dB) should be detected with K=5"

    def test_fold_info_present(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1
        assert 'max_fold_fraction' in detections[0].fold_info
        assert 'fold_snrs' in detections[0].fold_info
        assert len(detections[0].fold_info['fold_snrs']) == self.K

    def test_negative_freq_offset(self):
        """A negative offset should produce a detection at a lower
        frequency than a zero-offset signal (modulo spectral wrapping)."""
        d0, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=0.0, seed=60)
        dn, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=-500.0, seed=60)
        assert len(d0) >= 1 and len(dn) >= 1
        f0 = max(d0, key=lambda d: d[1])[0]
        fn = max(dn, key=lambda d: d[1])[0]
        raw_diff = fn - f0
        # Wrap to [-FS/2, FS/2) to handle spectral boundary crossing
        wrapped_diff = ((raw_diff + FS / 2) % FS) - FS / 2
        bin_width = FS / NFFT
        assert abs(wrapped_diff - (-500.0)) < 2 * bin_width, (
            f"Wrapped frequency shift {wrapped_diff:.1f} Hz, expected ~-500 Hz")

    def test_detection_margin_tight(self):
        """Tight margin (0.99) should still detect a strong signal."""
        detections, _, _ = _run_detect(self.K, snr_db=25.0, detection_margin=0.99)
        assert len(detections) >= 1

    def test_reproducibility(self):
        d1, _, _ = _run_detect(self.K, snr_db=20.0, seed=123)
        d2, _, _ = _run_detect(self.K, snr_db=20.0, seed=123)
        assert len(d1) == len(d2)
        if d1:
            assert d1[0][0] == pytest.approx(d2[0][0])
            assert d1[0][1] == pytest.approx(d2[0][1])


# ===================================================================
# K = 20 (long-range mode)
# ===================================================================
class TestSingleRateK20:
    K = 20

    def test_strong_signal_detected(self):
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1

    def test_weak_signal_detected(self):
        """K=20 integration should recover signals below K=5 threshold."""
        detections, _, _ = _run_detect(self.K, snr_db=6.0, seed=42)
        assert len(detections) >= 1, "Weak signal (6 dB) should be detected with K=20"

    def test_noise_only_no_detection(self):
        detections, noise_psd, _ = _run_detect(self.K, snr_db=-np.inf, seed=200)
        assert len(detections) == 0

    def test_k20_snr_exceeds_k5(self):
        """K=20 fold should yield higher SNR than K=5 for the same signal."""
        d5, _, _ = _run_detect(5, snr_db=15.0, seed=300)
        d20, _, _ = _run_detect(20, snr_db=15.0, seed=300)
        assert len(d5) >= 1 and len(d20) >= 1
        snr5 = max(d[1] for d in d5)
        snr20 = max(d[1] for d in d20)
        assert snr20 > snr5, f"K=20 SNR ({snr20:.1f}) should exceed K=5 ({snr5:.1f})"

    def test_fold_offsets_length(self):
        fo = _fold_offsets(self.K)
        assert len(fo) == self.K

    def test_frequency_accuracy(self):
        """Relative frequency accuracy: offset difference should be preserved."""
        d0, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=0.0, seed=300)
        dn, _, _ = _run_detect(self.K, snr_db=20.0, freq_offset_hz=-300.0, seed=300)
        assert len(d0) >= 1 and len(dn) >= 1
        f0 = max(d0, key=lambda d: d[1])[0]
        fn = max(dn, key=lambda d: d[1])[0]
        raw_diff = fn - f0
        wrapped_diff = ((raw_diff + FS / 2) % FS) - FS / 2
        bin_width = FS / NFFT
        assert abs(wrapped_diff - (-300.0)) < 2 * bin_width

    def test_max_fold_fraction_present(self):
        """Strong signal should have a reasonable max_fold_fraction."""
        detections, _, _ = _run_detect(self.K, snr_db=25.0)
        assert len(detections) >= 1
        assert 0.0 < detections[0].fold_info['max_fold_fraction'] <= 1.0


# ===================================================================
# Rate-switch helpers
# ===================================================================
_NOISE_POWER_DBFS = -40.0   # Same noise floor as SimConfig default


def _generate_rate_switch_iq(K: int, snr_db: float, change_point: int,
                             direction: str = 'A_to_B',
                             freq_offset_hz: float = 0.0,
                             seed: int = 42) -> tuple[np.ndarray, int]:
    """Generate IQ with a rate switch at the given change-point.

    Args:
        change_point: Number of gaps at the first rate before switching.
            0 = pure second rate, K-1 = pure first rate.
        direction: 'A_to_B' (rest→move) or 'B_to_A' (move→rest).

    Returns:
        (iq, samples_needed) tuple.
    """
    if direction == 'A_to_B':
        spacings_sec = ([TIP_REST] * change_point
                        + [TIP_MOVE] * (K - 1 - change_point))
    else:
        spacings_sec = ([TIP_MOVE] * change_point
                        + [TIP_REST] * (K - 1 - change_point))

    samples_needed = compute_segment_samples(N_WS, N_OL, K, N_EXACT, N_EXACT_MOVE)

    rng = np.random.default_rng(seed)
    noise_sigma = 10.0 ** (_NOISE_POWER_DBFS / 20.0)
    noise = noise_sigma * (
        rng.standard_normal(samples_needed)
        + 1j * rng.standard_normal(samples_needed)
    ) / np.sqrt(2.0)

    signal = np.zeros(samples_needed, dtype=np.complex128)
    if np.isfinite(snr_db):
        # Build pulse start times from spacing schedule
        pulse_times = [0.0]
        for s in spacings_sec:
            pulse_times.append(pulse_times[-1] + s)

        snr_linear = 10.0 ** (snr_db / 10.0)
        amp = noise_sigma * np.sqrt(snr_linear)
        t = np.arange(samples_needed, dtype=np.float64) / FS
        tone = amp * np.exp(2j * np.pi * freq_offset_hz * t)
        pulse_len = int(np.ceil(TP * FS))
        for pt in pulse_times:
            start = int(round(pt * FS))
            end = min(start + pulse_len, samples_needed)
            if start < samples_needed:
                signal[start:end] = tone[start:end]

    return (signal + noise).astype(np.complex64), samples_needed


def _run_detect_rate_switch(K: int, snr_db: float, change_point: int,
                            direction: str = 'A_to_B',
                            freq_offset_hz: float = 0.0,
                            seed: int = 42,
                            detection_margin: float = 0.90):
    """Full pipeline with multi-hypothesis fold_detect."""
    old_K = pulse_detector.K
    pulse_detector.K = K
    try:
        iq, samples_needed = _generate_rate_switch_iq(
            K, snr_db, change_point, direction, freq_offset_hz, seed)

        power, n_win = compute_stft_power(iq, N_W, N_OL, NFFT, W=W)
        hyps = build_hypothesis_indices(N_EXACT, K, n_win, N_B=N_EXACT_MOVE)

        fo = _fold_offsets(K, TIP_REST)
        cache = _evt_pool.setdefault((K, N_MOVE), {})

        return fold_detect(
            power, N, PF, FS, NFFT, N_W, N_OL, samples_needed,
            cache,
            fold_offsets=fo,
            W=W, Wf=Wf,
            detection_margin=detection_margin,
            hypotheses=hyps, N_B=N_MOVE,
        )
    finally:
        pulse_detector.K = old_K


# ===================================================================
# Rate-switch detection (K = 5)
# ===================================================================
class TestRateSwitchK5:
    """Verify rate-switch multi-hypothesis fold detection and SNR preservation."""
    K = 5

    # -- Detection correctness --

    def test_a_to_b_c2_detected(self):
        """A→B switch at change-point 2 should be detected."""
        detections, _, _ = _run_detect_rate_switch(self.K, snr_db=25.0, change_point=2)
        assert len(detections) >= 1
        assert 'A_to_B' in detections[0].hyp_label

    def test_b_to_a_c2_detected(self):
        """B→A switch at change-point 2 should be detected."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=2, direction='B_to_A')
        assert len(detections) >= 1
        assert 'B_to_A' in detections[0].hyp_label

    def test_pure_a_identified_with_dual_hypotheses(self):
        """Pure rate-A signal should be labelled 'A' under dual-rate search."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=self.K - 1)  # all gaps at rate A
        assert len(detections) >= 1
        assert detections[0].hyp_label == 'A'

    def test_pure_b_identified_with_dual_hypotheses(self):
        """Pure rate-B signal should be labelled 'B' under dual-rate search."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=0)  # all gaps at rate B
        assert len(detections) >= 1
        assert detections[0].hyp_label == 'B'

    # -- SNR preservation across rate switch --

    def test_a_to_b_snr_matches_pure_rate(self):
        """A→B switch fold SNR should be comparable to pure rate-A fold SNR.

        Both correctly-matched hypotheses sum K identical-amplitude pulse
        windows, so the fold gain is the same.
        """
        snr_in = 20.0
        seed = 500
        det_a, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=self.K - 1, seed=seed)
        det_sw, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=2, seed=seed)
        assert len(det_a) >= 1 and len(det_sw) >= 1
        snr_a = det_a[0][1]
        snr_sw = det_sw[0][1]
        assert abs(snr_sw - snr_a) < 3.0, (
            f"Switch SNR ({snr_sw:.1f} dB) differs from pure-A "
            f"({snr_a:.1f} dB) by more than 3 dB")

    def test_b_to_a_snr_matches_pure_rate(self):
        """B→A switch fold SNR should be comparable to pure rate-B fold SNR."""
        snr_in = 20.0
        seed = 501
        det_b, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=0, seed=seed)
        det_sw, _, _ = _run_detect_rate_switch(
            self.K, snr_db=snr_in, change_point=2, direction='B_to_A', seed=seed)
        assert len(det_b) >= 1 and len(det_sw) >= 1
        snr_b = det_b[0][1]
        snr_sw = det_sw[0][1]
        assert abs(snr_sw - snr_b) < 3.0, (
            f"Switch SNR ({snr_sw:.1f} dB) differs from pure-B "
            f"({snr_b:.1f} dB) by more than 3 dB")

    # -- Change-point identification --

    @pytest.mark.parametrize('c', [1, 2, 3])
    def test_a_to_b_change_point(self, c):
        """Each interior A→B change-point should be correctly identified."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=c, seed=600 + c)
        assert len(detections) >= 1
        assert detections[0].hyp_label == f'A_to_B_c{c}'

    @pytest.mark.parametrize('c', [1, 2, 3])
    def test_b_to_a_change_point(self, c):
        """Each interior B→A change-point should be correctly identified."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=c, direction='B_to_A', seed=700 + c)
        assert len(detections) >= 1
        assert detections[0].hyp_label == f'B_to_A_c{c}'

    # -- Edge cases --

    def test_noise_only_dual_rate(self):
        """Noise-only with dual-rate hypotheses should produce no detection."""
        detections, noise_psd, _ = _run_detect_rate_switch(
            self.K, snr_db=-np.inf, change_point=2, seed=99)
        assert len(detections) == 0
        assert np.isfinite(noise_psd)

    def test_max_fold_fraction_correct_switch(self):
        """Correct switch hypothesis should have a reasonable max_fold_fraction."""
        detections, _, _ = _run_detect_rate_switch(
            self.K, snr_db=25.0, change_point=2)
        assert len(detections) >= 1
        assert 0.0 < detections[0].fold_info['max_fold_fraction'] <= 1.0

    def test_fold_info_has_k_entries(self):
        """Rate-switch detection fold_info should contain K per-fold SNRs."""
        detections, _, _ = _run_detect_rate_switch(self.K, snr_db=25.0, change_point=2)
        assert len(detections) >= 1
        assert len(detections[0].fold_info['fold_snrs']) == self.K
